name: kindlink
description: A Flutter app that connects volunteers and people in need.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # UI & Fonts
  google_maps_flutter: ^2.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  another_flushbar: ^1.12.30

  # State management (if you were using it)
  provider: ^6.1.1
  file_picker: ^8.0.0

  # Icons and animations
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
