name: kindlink
description: A Flutter app that connects volunteers and people in need.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

 # -------------------------
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0
  cloud_functions: ^5.1.3

# -------------------------


  # UI & Maps
 
  google_maps_flutter: ^2.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  another_flushbar: ^1.12.30
  geolocator: ^10.1.0

  # -------------------------
  # State & Utils
  # -------------------------
  provider: ^6.1.2
  file_picker: ^8.1.2

  # -------------------------
  # Animations
  # -------------------------
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
